# Generated by Django 5.2.6 on 2025-09-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('jerseys', 'Jerseys'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('balls', 'Balls'), ('bags', 'Bags')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_iconic', models.BooleanField(default=False)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
