# Generated by Django 5.2.6 on 2025-09-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_stock_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jerseys', 'Jerseys'), ('pants', 'Pants'), ('jackets', 'Jackets'), ('shoes', 'Shoes'), ('balls', 'Balls')], default='update', max_length=20),
        ),
    ]
